### ISSUE TITLE
where the silent aim hitchance gone??

### ISSUE THREAD

**Issue by wal-ly** [CheeseOnGithub/cheese-hook#1]
silent aim hitchance disappeared why??

**Comment by wal-ly** [comment]
bruh add silent aim hitchance back

**Comment by t6c** [comment]
> bruh add silent aim hitchance back

just use the code from old commits, it hasn't gone for good

**Comment by CheeseOnGithub** [comment]
removed it because the silent aim broke

i will try to add silent aim back

**Comment by CheeseOnGithub** [comment]
removed hitchance, will add it back when i fix hit
