### ISSUE TITLE
Lagging AF

### ISSUE THREAD

**Issue by HXVRMXN-dev** [CheeseOnGithub/cheese-hook#2]
Lag/Freezing every few seconds probs due to bypass, mind fixing it g?

**Comment by CheeseOnGithub** [comment]
oh shit i forgot yeah ill try

**Comment by HXVRMXN-dev** [comment]
The new script update freezes the game

**Comment by CheeseOnGithub** [comment]
yeah the anticheat got updated

it shouldnt lag now can you test?

**Comment by HXVRMXN-dev** [comment]
my executor needs to be updated but ill let you know once it is

**Comment by HXVRMXN-dev** [comment]
freezes on krnl

**Comment by HXVRMXN-dev** [comment]
idk about my executor tho

**Comment by CheeseOnGithub** [comment]
yeah krnl is detected in combat warriors
it should work on fluxus tho?

btw can you give me ur discord so i can help

**Comment by HXVRMXN-dev** [comment]
No longer crashes once injected and no longer lagging with aimbot/aura
